// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const config =  {
    Auth: {
        Cognito: {
            userPoolId: `us-east-1_0Vl9UYuQ4` ,
            userPoolClientId: `7dcevn9nrs34fnpdiiui4h314p` , 
            region: `us-east-1`
        }
    }, 
    API: {
        GraphQL: {
          endpoint: 'https://h2uauxz2rfal7ifxovptgz6eky.appsync-api.us-east-1.amazonaws.com/graphql',
          region: 'us-east-1',
          defaultAuthMode: 'apiKey',
          apiKey: 'da2-dbp4h6xyvrcw5kkob5l74y3b2u'
        }
    }
};

export default config;