// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const config =  {
    API: {
        GraphQL: {
          endpoint: 'https://dr35ds4ckrb2znd7kbgdrzh6ei.appsync-api.us-east-2.amazonaws.com/graphql',
          region: 'us-east-2',
          defaultAuthMode: 'apiKey',
          apiKey: 'da2-qbqyn5sagrhntjywzl2jwpvuv4'
        }
    }
};

export default config;